### PR TITLE
Feature search pagination

### PR DESCRIPTION
**Pull request by victor-fdez**
Added pagination to search page of parroquias.

Note: I think that somehow you commited the git urls into the package.json. I don't think we should do that as it would be less readable and less clear which versions we are using. 

(fast comment)

### CODE REVIEW

**Comment by ricardoromanj** [comment]
Reviewed and approved. About the package.json, could've sworn I did not stage those changes for commit... or did I?
Any way, this will be a great opportunity to test the cicd capabilities of our server. Merging.

**Comment by ricardoromanj** [comment]
Development branch is being deployed. Currently deployed version has not stopped working. Everything is ok so far.

**Comment by ricardoromanj** [comment]
Deployment confirmed success. Can you verify?

**Comment by victor-fdez** [comment]
It's strange it seems as if the changes didn't go into the test.misas.online container. By the looks of CICD all went well there... haha

Actually after looking at the javascript for the website it seems that the container still contains the old code. The following code is the old code (proof 😛 )

``` javascript
"parroquias.search.js": function(r, a, e) {
                        console.log("Loaded parroquias directive!"), angular.module("parroquias").directive("parroquiasSearch", function() {
                            return {
                                restrict: "E",
                                templateUrl: "app/client/parroquias/views/parroquias.search.html",
                                controllerAs: "pssc",
                                controller: ["$scope", "$reactive", function r(a, e) {
                                    var i;
                                    return e(this).attach(a), i = this, i.helpers({
                                        parroquias: function t() {
                                            return Parroquias.find({})
                                        }
                                    }), i.subscribe("parroquias.search", function() {
                                        return [{}, i.getReactively("searchText")]
                                    }), console.log("parroquias search loaded")
                                }
                                ]
                            }
                        })
                    }
```

As for the stuff in package.json, I think maybe I did it but I guess it was probably done by some script we ran. I'll get to the bottom of this tomorrow :)

**Comment by ricardoromanj** [comment]
Added `docker-compose build` before restarting container. Seems to have worked now. Still, no app downtime when redeploying. App I think even reloads itself.

**Comment by victor-fdez** [comment]
Nice  :smile:

**Pull request merged**
