### PR TITLE
Feature parsing

### PR DESCRIPTION
**Pull request by victor-fdez**
Hi,

So here is the best so far that I could get it to today. It gets all churches but I forgot to get lat and longitudes, I think I will add that in another pull request, but for now this will do.

I also made the search look a little better, and also the parroquia view.

Thanks,

### CODE REVIEW

**Comment by victor-fdez** [comment]
After trying to move to the new application architecture with meteor 1.3.1 I gave up. So after tinkering I decided that we should migrate that new frame work in some months after everything has become more stable and all of the issues are ironed out. 

Some coffeescript files were changed to javascript. I guess we should convert everything to javascript in the future as to be more compatible with the new ecmascript standards or typescript :stuck_out_tongue:

**Comment by ricardoromanj** [comment]
Then, we will keep developing in meteor 1.2 for a while now? And in pure javascript then?

**Comment by victor-fdez** [comment]
List ya puedes hacerle pull a develop, solo que no creo que vaya a hacerse el deploy correcto. Tendras que installar shrinkwrap y correr npm install dentro del directorio de meteor antes que meteor corra, sino no correra correctamente... Saludos manana hablamos :smile:

**Comment by ricardoromanj** [comment]
Me queda una duda: Esto fue meteor 1.3 ya verdad? Sí tienes razón, no va a hacer bien el deployment. Tengo que cambiar el container... bueno, puedo hacer pruebas con este branch antes de hacer el merge. Gracias!

**Comment by victor-fdez** [comment]
Esto fue 1.3.1, si si quieres manana te digo que tendrias que agregarle a
deployment. El shrinkwrap es para asegurarnos que usamos las mismas
versiones de paquetes de npm en todos los servidores.

**Pull request merged**
